### ISSUE TITLE
Fix afk command blocking

### ISSUE THREAD

**Issue by mov51** [CapeCraft/capecraft-proxy#3]
The afk command needs to have the ability to be blocked in specific worldguard regions. prior to having the proxy setup we could do this by adding the command to the blocked commands flag, but this can no longer be done because it is now a bungee plugin and can not bee seen by the server.

Possible fixes:
**Implement a world guard flag for the use of AFK**
This seems like it would be the better but harder solution because it far more versatile and give us more control over the deny message and setup. Need to do more research on how this can be done and the problems that we could face.
**Implement the command front end on the paper servers**
This would be easier than setting up a world guard flag but would just allow u to block the command with worldguard, causing it to use it's own denial message for all blocked commands. Could be done by making the spigot command talk to the bungee server and keeping all of the afk state handling proxy side.

**Comment by james090500** [comment]
The code was implemented in 671e5f3

You just need to do world guard. /afk is now on Paper side
